name: Windows - H2S - CM - CUSTOM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
- name: Install dependencies
  run: |
    python.exe -m pip install --upgrade pip
    pip install chardet wheel  
    pip install git+https://github.com/monsterhunters/srtmerge.git --no-build-isolation

