name: Windows - H2S - CM - CUSTOM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install chardet wheel
          python -m pip install git+https://github.com/monsterhunters/srtmerge.git --no-build-isolation
