name: Windows - H2S - CM - CUSTOM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        shell: pwsh
        run: |
          python --version
          sudo pip3 install chardet
          pip install -r https://raw.githubusercontent.com/monsterhunters/sub/dev/requirements.txt

