name: Windows - H2S - CM - CUSTOM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |          
      - name: Install dependencies
          run: |
            pip install --upgrade pip setuptools wheel
            pip install chardet
            pip install --no-build-isolation git+https://github.com/monsterhunters/srtmerge.git
            pip install -r https://raw.githubusercontent.com/monsterhunters/sub/dev/requirements.txt --ignore-installed srtmerge

            Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/directcm720custom.bat" -OutFile "directcm720custom.bat"
            cmd /c directcm720custom.bat
