name: Windows - H2S - CM - CUSTOM

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install chardet
          python -m pip install --no-use-pep517 git+https://github.com/monsterhunters/srtmerge.git
          python -m pip install -r https://raw.githubusercontent.com/monsterhunters/sub/dev/requirements.txt --ignore-installed srtmerge
