name: Windows - H2S - CM - 720 - Yellow

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/directcm720yellow.bat" -OutFile "directcm720yellow.bat"
          cmd /c directcm720yellow.bat
