
name: Windows - H2S - CM - NEW

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          python -m pip install --upgrade pip
          pip install yagmail
          pip install chardet
          pip install -v git+https://github.com/monsterhunters/srtmerge.git
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/directcm720new.bat" -OutFile "directcm720new.bat"
          cmd /c directcm720new.bat
