name: Windows - Download - Torrent

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/downloadtr.bat" -OutFile "downloadtr.bat"
          cmd /c downloadtr.bat
